name: sync-repo

on:
 schedule:
   - cron: '35 */2 * * *'
 workflow_dispatch:
 watch:
   types: started
 repository_dispatch:
   types: 6Svip120apk69

jobs:
  mirror:
    env:
      PAT: ${{ secrets.PAT }} #当前库的pat
      DEFAULT_DST: github/6Svip120apk69
      DEFAULT_RENAME_FMT: 's/(.*)/${SRC_TYPE}_${SRC_ACCOUNT}_\1/g'
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: | 
            "${{ github.workspace }}/.cache"
          key: ${{ runner.os }}-cache-actions
          restore-keys: |
            ${{ runner.os }}-cache-actions

      - name: mirror gitee/q8qsTAUA
        uses: fakedon/hub-mirror-action@fakedon
        with:
          src: gitee/q8qsTAUA
          dst: ${{ env.DEFAULT_DST }}
          dst_key: ${{ secrets.ZIYE_GITHUB_SSH_KEY }}
          dst_token: ${{ secrets.ZIYE_GITHUB_TOKEN }}
          static_list: "80osSwxOLsosKAEA"
          dst_account_type: user
          force_update: true
          rename_dst: true
          # clone_style: https
          rename_fmt: ${{ env.DEFAULT_RENAME_FMT }}
